### ISSUE TITLE
User friendly names

### ISSUE THREAD

**Issue by sambolias** [alasconnect/data-validation#1]
Some user facing functions are using internal names - most noticeably `fromVCtx`. Since that is being proposed as the way to create smart constructors that yields Proof the name should reflect that, or a more general usage. 

I figure some terms should be agreed on to what we call the process of creating a proof, probably validation, then use that consistently in the interface.

The other wording I find a little unclear is dispute and refute. It seems like we use disputes as standalone checks, and refutes in transforming checks. Though if dispute and refute are documented and used consistently that works too.

**Comment by devinlyons** [comment]
We definitely need to make sure the documentation is clear on what these functions do. Other than that though, I think the names fit Haskell.

**Comment by sambolias** [comment]
The docs are coming together nicely and others will be reviewing. I'm going to close this. As long as no other reviewers see a problem with names I can live with these.
