### ISSUE TITLE
Minor inconsistencies in haddock docs

### ISSUE THREAD

**Issue by sambolias** [alasconnect/data-validation#12]
The docs on came together great on [hackage](https://hackage.haskell.org/package/data-validation-0.1.0.0/docs/Data-Validation.html). Noted below are some minor inconsistencies that stuck out: 
- The code highlighting does not seem to pick up backticks, I think `@` wrapping for monospace is what is needed [here](https://github.com/alasconnect/data-validation/blob/2ba54361c2674388af171313af6e357fa888960c/src/Data/Validation.hs#L89)
- The `c` here should be and `f` to align with above definition [here](https://github.com/alasconnect/data-validation/blob/2ba54361c2674388af171313af6e357fa888960c/src/Data/Validation.hs#L108)
- The `>>` renders a single `>`, writing a single would only highlight [here](https://github.com/alasconnect/data-validation/blob/2ba54361c2674388af171313af6e357fa888960c/src/Data/Validation.hs#L163)
- The `*` are actually rendering `*` instead of desired list itemization [here](https://github.com/alasconnect/data-validation/blob/2ba54361c2674388af171313af6e357fa888960c/src/Data/Validation.hs#L377)

**Comment by devinlyons** [comment]
I think the solution to the 4th points is here: https://haskell-haddock.readthedocs.io/en/latest/markup.html#constructors-and-record-fields.
