### ISSUE TITLE
Cabal Check CI

### ISSUE THREAD

**Issue by sambolias** [alasconnect/data-validation#36]
`cabal check` can be used to ensure the cabal file is in correct format for Hackage. It is possible to have malformed cabal that still works, so it would be nice if `cabal check` could be added to CI pipeline. Not sure at this time what that would entail.

**Comment by boj** [comment]
@sambolias You'd just add a new section somewhere [around here](https://github.com/alasconnect/data-validation/commit/a506c1a9019dd52514c2270c9dc43c1919835cca#diff-c09cc8dc973415b1221308559b96942a1c4b872e690bf360fc22d9b42822d519R38-R46) to do the check.
