### ISSUE TITLE
Call For General Validators

### ISSUE THREAD

**Issue by devinlyons** [alasconnect/data-validation#4]
What general validators should we add to the lib? Here's my list so far:

 - IsEqual - using the `Eq` type class.
 - IsNotEqual - using the `Eq` type class.
 - isLessThan - using the `Ord` type class.
 - isGreaterThan - using the `Ord` type class.
 - matchesRegex - regular expression checking.
 - hasElem - based on `elem`.
 - doesNotHaveElem - based on `elem`.
 - hasAll - checks every element in a foldable.
 - hasAny - check every element in a foldable.

**Comment by sambolias** [comment]
- This seems to be missing `isRequired` and `optional`.
- It should also have `isNull` and `isNotNull`.
- Also `hasAny` and `hasAll` indicate to me that it is checking if a list has any element from another list or has all from another list respectively. If I am right on that there should also be `anyWithFact` and `allWithFact` that work like `any` and `all` from `Data.List`

**Comment by sambolias** [comment]
I really like `matchesWithRegex` - I remember Brian talking me out of regex when I was very green to haskell, and there was some problems with some regex libs. I'm curious what regex lib you have in mind?

**Comment by devinlyons** [comment]
`isRequired`, `optional`, `isNull`, and `isNotNull` are already in the lib. `hasAny` will take a list and check each element with a function. If any pass, they validation passes. `hasAll` does the same thing except all elements must pass.

**Comment by devinlyons** [comment]
As or Regex, I haven't decided yet. I'm not even sure I'm going to add that check.

**Comment by boj** [comment]
As far as I know existing regex libs are wrappers around native PCRE libs anyways, and therefore won't work for frontend code like Reflex.

**Comment by sambolias** [comment]
If this is in addition to what is in lib now there are duplicates. Also `has` denotes contents, it seems bad language to use has for some boolean check, especially alongside a correctly used has like `hasElem`

**Comment by devinlyons** [comment]
Native Regex lib: https://github.com/haskell-hvr/regex-tdfa!

**Comment by devinlyons** [comment]
I added those functions as `ifAny`, `ifAll`, and `ifEach`.
