### ISSUE TITLE
Frontend build failing to enter nix-shell

### ISSUE THREAD

**Issue by sambolias** [alasconnect/data-validation#6]
Could not enter reflex/ghcjs nix-shell for TAS frontend build using data-validation. Final error message not informative to me, but suspect regex-tdfa https://hackage.haskell.org/package/regex-tdfa. 
```shell
Build with /nix/store/47fs1p9v07wnqp044ldp22i79njw6r2j-ghcjs-8.6.0.1.
unpacking sources
unpacking source archive /nix/store/wnhbyj3x1h7z16grwji42wzcdlb9lmp0-source/.
unpacker produced multiple directories
builder for '/nix/store/39ir4755pb52ri1lfr21praw7fx7shqm-data-validation-0.1.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/83nbqfqgvfl8nrgld7jrmcs8jfrc4r7l-ghcjs-8.6.0.1-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/83nbqfqgvfl8nrgld7jrmcs8jfrc4r7l-ghcjs-8.6.0.1-with-packages.drv' failed   
```

**Comment by sambolias** [comment]
When testing without the regex lib found that the `data-validation-internal` library was not exposing `Data.Validation.Internal` to main library as it should. This caused no problem with ghc builds, but with the ghcjs build it gave the following error output
```shell
building
Preprocessing library 'data-validation-internal' for data-validation-0.1.0.0..
Building library 'data-validation-internal' for data-validation-0.1.0.0..
Preprocessing library for data-validation-0.1.0.0..
Building library for data-validation-0.1.0.0..

src/Data/Validation.hs:83:1: error:
Could not find module ‘Data.Validation.Internal’
Perhaps you haven't installed the "js" libraries for package ‘data-validation-0.1.0.0’?
Use -v to see a list of the files searched for.
   |
83 | import Data.Validation.Internal
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builder for '/nix/store/dd21smp3wskn7zwvx9ldxzbjk44461b7-data-validation-0.1.0.0.drv' failed with exit code 1 cannot build derivation '/nix/store/2qdabnadq4k1z36p0dycxsm41hxj052z-ghcjs-8.6.0.1-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/2qdabnadq4k1z36p0dycxsm41hxj052z-ghcjs-8.6.0.1-with-packages.drv' failed 
```

**Comment by Mikolaj** [comment]
Was the internal library public? If not, I think it's correctly not being exported from the package. I don't remember in which GHC in changed, but possibly it changed in GHCJS earlier.

**Comment by sambolias** [comment]
It is not intentionally public, but we had issues with ghcjs/reflex-platform and the internal module so we exposed it to make this library more flexible. See the attached PR for more details.

**Comment by Mikolaj** [comment]
Got it. Just a helpful remark that starting with some newer GHC (and probably earlier than that in GHCJS), you can mark an internal library public (as in this incomplete documentation: https://cabal.readthedocs.io/en/3.4/cabal-package.html#pkg-field-library-visibility) and the remaining libraries (the private ones) stopped being visible outside the package. That may be the mystery behind the bug mentioned in the PRs.
